blank_issues_enabled: false
contact_links:
  - name: Robotics StackExchange
    about: Get help with individual issues or questions from the Robotics community.
    url: https://robotics.stackexchange.com/
